
name: CI/build+test


on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Compile
        run: |
          git submodule init
          ls
          cmake ./
          make
      - name : Basic Test
        run: |
          cmake ./
          make
          echo "1+1" | ./calculator
          echo "(1+1)" | ./calculator
          echo "1*1" | ./calculator
          echo "3/2" | ./calculator
          echo "1-2" | ./calculator
      - name : Advanced Test
        run: |
          cmake ./
          cmake build ./
          echo "((1+1))" | ./calculator
          echo "(1+1)*2" | ./calculator
          echo "(1+1)^2" | ./calculator
          echo "((2-1)*2+1)^2" | ./calculator
          echo "(((2-1)*2+1)^2-1)/2" | ./calculator
          echo "-1+1" | ./calculator
          echo "1+(-1)" | ./calculator
          echo "(((-2-1)*2+1)^2-1)/2" | ./calculator
          echo "0.1-1" | ./calculator
          echo "0.1-0.1" | ./calculator
          echo "0.1^0.1" | ./calculator
          echo "sqrt9" | ./calculator
          echo "sqrt(8+1)" | ./calculator
          echo "8^(1/3)" | ./calculator
          echo "8^-1" | ./calculator
